name: Release package to NPM 🚀
on:
    release:
        types: [published]
jobs:
    build:
        permissions:
            contents: read
            id-token: write
            packages: write
            attestations: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
        
            - name: Install pnpm LTS 
              uses: pnpm/action-setup@v4
              with:
                version: "latest"
                # Prevent automatic instalation of resources at the current point
                run_install: false

            - name: Install Node LTS
              uses: actions/setup-node@v4
              with:
                node-version: "latest"
                cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile
    publish-npm:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install pnpm LTS 
              uses: pnpm/action-setup@v4
              with:
                version: "latest"
                # Prevent automatic instalation of resources at the current point
                run_install: false

            - name: Install Node LTS
              uses: actions/setup-node@v4
              with:
                node-version: "latest"
                cache: pnpm
                registry-url: "https://registry.npmjs.org"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            #Verify npm configuration (for debugging)
            - name: Debug npm configuration
              run: pnpm config list

            #Verify login configuration (for debugging)
            - name: Debug npm login configuration
              run: pnpm whoami
              env:
                NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}

            - name: Publish to NPM 🚀
              run: pnpm publish --no-git-checks --access public --dry-run
              env: 
                NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}
  
